name: Keep Render App Alive

on:
  schedule:
    # Every 10 minutes
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl --silent --show-error --fail \
            https://statdium-fifa-world-cup-2026.onrender.com/ \
            > /dev/null
